default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gemsweeper_development

test:
  <<: *default
  database: gemsweeper_test

production:
  <<: *default
  database: gemsweeper_production
  username: gemsweeper
  password: <%= ENV['YOUR_APP_DATABASE_PASSWORD'] %>